# Generated by Django 3.2.7 on 2021-10-11 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('usuarioNombre', models.CharField(db_column='nombre', max_length=100, verbose_name='Nombre del usuario')),
                ('usuarioApellido', models.CharField(db_column='apellido', max_length=100, verbose_name='Apellido del usuario')),
                ('usuarioCorreo', models.EmailField(db_column='correo', max_length=200, unique=True, verbose_name='Correo del usuario')),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'DOCENTE'), (3, 'ALUMNO')], db_column='tipo', verbose_name='Tipo del usuario')),
                ('password', models.TextField(verbose_name='contraseña del Usuario')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('cursoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('cursoNombre', models.CharField(db_column='nombre', max_length=100)),
                ('cursoSemestre', models.IntegerField(db_column='semestre')),
                ('docente', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='docenteCurso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='CalificacionesModel',
            fields=[
                ('calificacionId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('calificacionDetalle', models.TextField(db_column='detalle', max_length=200, null=True)),
                ('calificacionFecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('calificacionTipo', models.IntegerField(choices=[(1, 'EXAMEN'), (2, 'TAREA')], db_column='tipo')),
                ('calificacionNota', models.DecimalField(db_column='nota', decimal_places=2, max_digits=2)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='cursoCalificacion', to='sistema.cursomodel')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarioCalificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
    ]
