# Generated by Django 3.2.7 on 2021-10-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='usuarioMatricula',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calificacionesmodel',
            name='calificacionNota',
            field=models.DecimalField(db_column='nota', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='password',
            field=models.TextField(verbose_name='Contraseña del Usuario'),
        ),
    ]
