# Generated by Django 3.2.7 on 2021-10-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_matriculaToCalificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionesmodel',
            name='matricula',
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='matricula',
            field=models.BooleanField(default=True),
        ),
    ]
