# Generated by Django 3.2.7 on 2021-10-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_matriculaenusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarioAlumno', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='cursoAlumno', to='sistema.cursomodel')),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
