# Generated by Django 3.2.7 on 2021-10-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alumnosmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='usuarioFoto',
            field=models.ImageField(db_column='foto', null=True, upload_to='usuarios/'),
        ),
    ]
